# poetry configuration file

[project]
name = "testing-dynaconf"
version = "0.1.0"
description = "understand dynaconf full capabilities"
authors = [
    {name = "Juan Aguilar",email = "juanantonioaguilar@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dynaconf (>=3.2.10,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
ipython = "^9.0.2"
ipdb = "^0.13.13"

